site_name: Onyx
site_url: https://climb-tre.github.io/onyx-client/
repo_url: https://github.com/CLIMB-TRE/onyx-client/
site_author: CLIMB-TRE

theme:
  name: material
  palette:
    primary: black
    accent: black

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: sphinx
            docstring_section_style: spacy
            show_source: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Documentation:
    - Command-line interface: cli.md
    - Python API: 
      - OnyxConfig: api/config.md
      - OnyxClient: api/client.md
      - OnyxField: api/field.md
      - Examples: api/examples.md
  - CLIMB-TRE: https://climb-tre.github.io