site_name: Onyx-client
site_url: https://climb-tre.github.io/onyx-client/
repo_url: https://github.com/CLIMB-TRE/onyx-client/
repo_name: CLIMB-TRE/onyx-client
site_author: CLIMB-TRE

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.top
    # - toc.integrate
    - content.code.copy

extra:
  version:
    provider: mike

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: spacy
            show_source: false
            members_order: source
  - with-pdf:
      output_path: onyx-client.pdf
      cover_subtitle: ""

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Command-line interface: 
    - Getting started: cli/getting-started.md
    - Documentation: cli/documentation.md
  - Python API: 
    - Documentation:
      - OnyxClient: api/documentation/client.md
      - OnyxConfig: api/documentation/config.md
      - OnyxEnv: api/documentation/env.md
      - OnyxField: api/documentation/field.md
  - CLIMB-TRE: https://climb-tre.github.io