site_name: Onyx
site_url: https://climb-tre.github.io/onyx-client/
repo_url: https://github.com/CLIMB-TRE/onyx-client/
site_author: CLIMB-TRE

theme:
  name: material

nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Documentation:
    - Command-line interface: cli.md
    - Python API: api.md
  - Further Guidance:
    - Examples: examples.md