site_name: Onyx-client
site_url: https://climb-tre.github.io/onyx-client/
repo_url: https://github.com/CLIMB-TRE/onyx-client/
repo_name: CLIMB-TRE/onyx-client
site_author: CLIMB-TRE

theme:
  name: material
  palette:
    primary: black
    accent: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: spacy
            show_source: false
            members_order: source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Getting started: getting-started.md
  - Command-line interface: cli.md
  - Python API: 
    - OnyxConfig: api/config.md
    - OnyxClient: api/client.md
    - OnyxField: api/field.md
  - CLIMB-TRE: https://climb-tre.github.io