site_name: Onyx Documentation
site_url: https://climb-tre.github.io/onyx-client/

theme:
  name: material

nav:
  - Home: ../README.md
  - Installation Guide: install.md
  - Documentation:
    - Command-line interface: cli.md
    - Python API: api.md