site_name: Onyx
site_url: https://climb-tre.github.io/onyx-client/
repo_url: https://github.com/CLIMB-TRE/onyx-client/
site_author: CLIMB-TRE

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            docstring_section_style: spacy
            show_source: false
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Documentation:
    - Command-line interface: cli.md
    - Python API: 
      - OnyxConfig: api/config.md
      - OnyxClient: api/client.md
  - Further Guidance:
    - Examples: examples.md